
SPEC = {
    "NUM_STAGES": 3,
    "PATCH_SIZE": [7, 3, 3],
    # "PATCH_SIZE": [17, 3, 3],
    "PATCH_STRIDE": [4, 2, 2],
    # "PATCH_STRIDE": [8, 2, 2],
    "PATCH_PADDING": [2, 1, 1],
    # "DIM_EMBED": [64, 128, 64],
    "DIM_EMBED": [8, 24, 48],
    # "DIM_EMBED": [32,  , 384],
    "NUM_HEADS": [1, 3, 6],
    # "DEPTH": [1, 2, 10],
    "DEPTH": [2, 3, 5],
    "MLP_RATIO": [4.0, 4.0, 4.0],
    "ATTN_DROP_RATE": [0.0, 0.0, 0.0],
    "DROP_RATE": [0.0, 0.0, 0.0],
    "DROP_PATH_RATE": [0.0, 0.0, 0.1],
    "QKV_BIAS": [True, True, True],
    "CLS_TOKEN": [False, False, False],
    "POS_EMBED": [False, False, False],
    "QKV_PROJ_METHOD": ['dw_bn', 'dw_bn', 'dw_bn'],
    # "QKV_PROJ_METHOD": ['avg', 'avg', 'avg'],
    "KERNEL_QKV": [3, 3, 3],
    "PADDING_KV": ["same", "same", "same"],
    "STRIDE_KV": [2, 2, 2],
    "PADDING_Q": ["same", "same", "same"],
    "STRIDE_Q": [1, 1, 1],
}
